name: Publish to npm

on:
  push:
    tags:
      - 'v*'
      - 'V*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")

          # Publish with 'beta' tag only if version contains '-beta'
          if [[ "$VERSION" == *-beta* ]]; then
            TAG="beta"
          else
            TAG="latest"
          fi

          echo "Publishing version $VERSION with tag $TAG"
          npm publish --access public --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
